Update the paker build workflow

diff --git a/.github/workflows/Packer-build.yml b/.github/workflows/Packer-build.yml
--- a/.github/workflows/Packer-build.yml
+++ b/.github/workflows/Packer-build.yml
@@ -9,7 +9,7 @@ on:
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
-
+    
     services:
       postgres:
         image: postgres:alpine
@@ -35,7 +35,6 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
-
       - name: Cache node_modules
         uses: actions/cache@v3
         with:
@@ -76,8 +75,8 @@ jobs:
       - name: Setup AWS CLI
         uses: aws-actions/configure-aws-credentials@v1
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
       - name: Authenticate to Google Cloud
@@ -104,5 +103,22 @@ jobs:
             -var "aws_region=${{ secrets.AWS_REGION }}" \
             -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
             -var "gcp_zone=${{ secrets.GCP_ZONE }}" \
-            -var "gcp_demo_account=${{ secrets.GCP_DEMO_ACCOUNT }}" \
+            -var "gcp_destination_project_id=${{ secrets.GCP_DESTINATION_PROJECT_ID }}" \
             csye-6225.pkr.hcl
+      - name: Share AMI  Dev and Demo accounts
+        run: |
+                  AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=csye-*" --query 'Images[-1].ImageId' --output text)
+                  aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\":[{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEV }}\"},{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEMO }}\"}]}"
+    
+      - name: Share GCP Image with Demo Project
+        run: |
+                          IMAGE_NAME=$(gcloud compute images list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~csye-*" --sort-by="~creationTimestamp" --limit=1 --format="value(NAME)")
+                          echo "Extracted Image Name: $IMAGE_NAME"
+                          if [ -z "$IMAGE_NAME" ]; then
+                            echo "Error: No image found!"
+                            exit 1
+                          fi
+                          gcloud compute images add-iam-policy-binding "$IMAGE_NAME" \
+                            --project="${{ secrets.GCP_PROJECT_ID }}" \
+                            --member="serviceAccount:${{ secrets.GCP_DEMO_ACCOUNT }}" \
+                            --role="roles/compute.imageUser"
