Update packer build workflow file

diff --git a/.github/workflows/Packer-build.yml b/.github/workflows/Packer-build.yml
--- a/.github/workflows/Packer-build.yml
+++ b/.github/workflows/Packer-build.yml
@@ -105,3 +105,20 @@ jobs:
             -var "gcp_zone=${{ secrets.GCP_ZONE }}" \
             -var "gcp_destination_project_id=${{ secrets.GCP_DESTINATION_PROJECT_ID }}" \
             csye-6225.pkr.hcl
+      - name: Share AMI  Dev and Demo accounts
+        run: |
+                  AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=csye-*" --query 'Images[-1].ImageId' --output text)
+                  aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\":[{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEV }}\"},{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEMO }}\"}]}"
+    
+      - name: Share GCP Image with Demo Project
+        run: |
+                          IMAGE_NAME=$(gcloud compute images list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~csye-*" --sort-by="~creationTimestamp" --limit=1 --format="value(NAME)")
+                          echo "Extracted Image Name: $IMAGE_NAME"
+                          if [ -z "$IMAGE_NAME" ]; then
+                            echo "Error: No image found!"
+                            exit 1
+                          fi
+                          gcloud compute images add-iam-policy-binding "$IMAGE_NAME" \
+                            --project="${{ secrets.GCP_PROJECT_ID }}" \
+                            --member="serviceAccount:${{ secrets.GCP_DEMO_ACCOUNT }}" \
+                            --role="roles/compute.imageUser"
